services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      MODEL_PATH: ${MODEL_PATH}
      GIGACHAT_API_KEY: ${GIGACHAT_API_KEY}
    volumes:
      - ./models/vosk-model-ru-0.42:/var/copium-robot/model
