name: Go Pipeline

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  create:
    tags: [ 'v*' ]  # Trigger deploy on semantic version tags

env:
  VOSK_PATH: "${{ github.workspace }}/pkg/vosk-linux-x86_64-0.3.45"
  LD_LIBRARY_PATH: "${{ github.workspace }}/pkg/vosk-linux-x86_64-0.3.45"
  CGO_CPPFLAGS: "-I ${{ github.workspace }}/pkg/vosk-linux-x86_64-0.3.45"
  CGO_LDFLAGS: "-L ${{ github.workspace }}/pkg/vosk-linux-x86_64-0.3.45"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test -v -race ./...
